using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lighthouse.Enums
{
    public enum Countries
    {
        [Display(Name = "Restricted Country")]
        RestrictedCountry,
        Albania,
        Andorra,
        Angola,
        Argentina,
        Armenia,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Barbados,
        Belarus,
        Belgium,
        Belize,
        Benin,
        Bolivia,
        Bosnia,
        Botswana,
        Brazil,
        Bulgaria,
        [Display(Name = "Burkina Faso")]
        BurkinaFaso,
        Burundi,
        [Display(Name = "Cabo Verde")]
        CaboVerde,
        Cambodia,
        Cameroon,
        Canada,
        Chad,
        Chile,
        [Display(Name = "Democratic Republic Of The Congo")]
        DemocraticRepublicOfTheCongo,
        [Display(Name = "Republic Of The Costa Rica")]
        RepublicOfTheCostaRica,
        [Display(Name = "Cote D'Ivoire")]
        CoteDIvoire,
        Croatia,
        Cuba,
        Cyprus,
        Czechia,
        Denmark,
        Dominica,
        [Display(Name = "Dominican Republic")]
        DominicanRepublic,
        Ecuador,
        [Display(Name = "El Salvador")]
        ElSalvador,
        [Display(Name = "Equatorial Guinea")]
        EquatorialGuinea,
        Estonia,
        Eswatini,
        Fiji,
        Finland,
        France,
        Gabon,
        Gambia,
        Georgia,
        Germany,
        Ghana,
        Greece,
        Grenada,
        Guatemala,
        Guinea,
        [Display(Name = "Guinea Bissau")]
        GuineaBissau,
        Guyana,
        Haiti,
        Honduras,
        Hungary,
        Iceland,
        Ireland,
        Israel,
        Italy,
        Jamaica,
        Japan,
        Kiribati,
        Kosovo,
        Kyrgyzstan,
        Latvia,
        Lebanon,
        Lesotho,
        Liberia,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Madagascar,
        Malawi,
        Malta,
        MarshallIslands,
        Mauritius,
        Micronesia,
        Moldova,
        Monaco,
        Mongolia,
        Montenegro,
        Morocco,
        Mozambique,
        Namibia,
        Nauru,
        Nepal,
        Netherlands,
        NewZealand,
        Nicaragua,
        Niger,
        NorthMacedonia,
        Norway,
        Palau,
        Panama,
        PapuaNewGuinea,
        Paraguay,
        Peru,
        Philippines,
        Poland,
        Portugal,
        Romania,
        Russia,
        Rwanda,
        SaintKittsAndNevis,
        SaintLucia,
        SaintVincentAndTheGrenadines,
        Samoa,
        SanMarino,
        SaoTomeAndPrincipe,
        Senegal,
        Serbia,
        Seychelles,
        SierraLeone,
        Singapore,
        Slovakia,
        Slovenia,
        SolomonIslands,
        SouthAfrica,
        SouthKorea,
        SouthSudan,
        Spain,
        Suriname,
        Sweden,
        Switzerland,
        Taiwan,
        Thailand,
        TimorLeste,
        Togo,
        Tonga,
        TrinidadAndTobago,
        Tuvalu,
        Uganda,
        Ukraine,
        UnitedKingdom,
        UnitedStatesOfAmerica,
        Uruguay,
        Vanuatu,
        Venezuela,
        Zambia,
        Zimbabwe
    }
}